---
version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "[%(asctime)s] [%(levelname)s] %(module)s - %(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: $LOG_LEVEL
    formatter: simple
    stream: ext://sys.stdout
    filters: [sensitive_info]
  file_handler:
    class: logging.FileHandler
    filename: app.log
    level: $LOG_LEVEL
    formatter: simple
    filters: [sensitive_info]

filters:
  sensitive_info:
    (): conf.logging.SensitiveInfoFilter
    sensitive_words: [password, secret, username, token, key]

root:
  level: $LOG_LEVEL
  handlers: [console_handler, file_handler]